function New-UninstallScript {
    param(
        [hashtable]$Config,
        [string]$OutputPath
    )

    $installDir = $Config.InstallDir
    $webAlias   = $Config.WebAlias
    $msiName    = Split-Path $Config.MsiPath -Leaf
    $features   = (Get-IISFeatures) -join "',`n        '"

    $script = @"
#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Uninstalls Aras Innovator and optionally removes SQL Server and IIS features.
    Generated by Aras Easy Installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm').
#>

param(
    [switch]`$RemoveSqlServer,
    [switch]`$RemoveIIS,
    [switch]`$Force
)

`$ErrorActionPreference = 'Stop'

Write-Host ''
Write-Host '  Aras Innovator Uninstaller' -ForegroundColor Cyan
Write-Host '  =========================='  -ForegroundColor Cyan
Write-Host ''

# -- Uninstall Aras MSI --

Write-Host '  [1/3] Uninstalling Aras Innovator...' -ForegroundColor White

`$msiProducts = Get-WmiObject -Class Win32_Product -Filter "Name LIKE '%Aras%Innovator%'" -ErrorAction SilentlyContinue
if (`$msiProducts) {
    foreach (`$product in `$msiProducts) {
        Write-Host "    Removing: `$(`$product.Name)" -ForegroundColor DarkGray
        `$product.Uninstall() | Out-Null
    }
    Write-Host '    + Aras Innovator uninstalled' -ForegroundColor Green
} else {
    Write-Host '    i No Aras Innovator MSI found, skipping' -ForegroundColor DarkGray
}

# Remove IIS site/application
try {
    Import-Module WebAdministration -ErrorAction SilentlyContinue
    if (Get-WebApplication -Name '$webAlias' -ErrorAction SilentlyContinue) {
        Remove-WebApplication -Name '$webAlias' -Site 'Default Web Site' -ErrorAction SilentlyContinue
        Write-Host "    + Removed IIS application: $webAlias" -ForegroundColor Green
    }
} catch {}

# Remove install directory
if (Test-Path '$installDir') {
    if (`$Force -or (Read-Host "  ? Delete install folder $installDir? [y/N]").Trim().ToLower() -eq 'y') {
        Remove-Item '$installDir' -Recurse -Force
        Write-Host "    + Removed: $installDir" -ForegroundColor Green
    }
}

# -- Optionally remove SQL Server --

Write-Host ''
Write-Host '  [2/3] SQL Server...' -ForegroundColor White

if (`$RemoveSqlServer) {
    `$sqlService = Get-Service -Name 'MSSQLSERVER' -ErrorAction SilentlyContinue
    if (`$sqlService) {
        Stop-Service -Name 'MSSQLSERVER' -Force -ErrorAction SilentlyContinue
        `$sqlProducts = Get-WmiObject -Class Win32_Product -Filter "Name LIKE '%SQL Server%'" -ErrorAction SilentlyContinue
        foreach (`$p in `$sqlProducts) {
            Write-Host "    Removing: `$(`$p.Name)" -ForegroundColor DarkGray
            `$p.Uninstall() | Out-Null
        }
        Write-Host '    + SQL Server removed' -ForegroundColor Green
    } else {
        Write-Host '    i SQL Server service not found' -ForegroundColor DarkGray
    }
} else {
    Write-Host '    i Skipping SQL Server removal (use -RemoveSqlServer to include)' -ForegroundColor DarkGray
}

# -- Optionally disable IIS features --

Write-Host ''
Write-Host '  [3/3] IIS Features...' -ForegroundColor White

if (`$RemoveIIS) {
    `$features = @(
        '$features'
    )
    foreach (`$f in `$features) {
        try {
            Disable-WindowsOptionalFeature -Online -FeatureName `$f -NoRestart -ErrorAction SilentlyContinue | Out-Null
        } catch {}
    }
    Write-Host '    + IIS features disabled' -ForegroundColor Green
} else {
    Write-Host '    i Skipping IIS removal (use -RemoveIIS to include)' -ForegroundColor DarkGray
}

Write-Host ''
Write-Host '  Uninstall complete.' -ForegroundColor Green
Write-Host '  A reboot may be required for some changes to take effect.' -ForegroundColor DarkGray
Write-Host ''
"@

    $script | Out-File -FilePath $OutputPath -Encoding UTF8 -Force
    return $OutputPath
}

Export-ModuleMember -Function New-UninstallScript
